format="$directory$battery$character"

palette='catpuccin'

[palettes.catpuccin]

base = "#303446"
teal = '#81c8be'
mauve = "#ca9ee6"
lavender = "#babbf1"

[directory]
truncate_to_repo = true
style = 'bold mauve'


[character]

format = '[><>  ](bold teal)'

