format="$directory$battery$character"

palette='northstar'

[palettes.northstar]

white = '#fff7e0'
pink = '#e49c97'
purple = '#a37592'
black = '#434959'

[directory]
truncate_to_repo = true
style = 'bold pink'


[character]

format = '[󰅶  ](bold white)'

