theme = "nord_nobg"



[editor.file-picker]
hidden = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor]
auto-save = true
auto-completion = true

[editor.statusline]
left = ["mode" , "spinner", "position"]
right = ["diagnostics" , "selections" , "total-line-numbers" , "file-name"]
separator = "|"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

