import = ["/home/zayaan/.config/alacritty/mountain.toml"]

[cursor.style]
shape = "Beam"
blinking = "On"

[font]
size = 12.0

[font.normal]
family = "Iosevka Nerd Font"
style = "Regular"

[shell]
program = "/bin/fish"

[window]
dynamic_padding = true
dynamic_title = true
opacity = 0.4

[window.padding]
x = 10
y = 10
