format = """
[░▒▓](#262626)\
[  ](bg:#363636 fg:#e7e7e7)\
[](bg:#e7e7e7 fg:#363636)\
$directory\
[](fg:#e7e7e7 bg:#828aac)\
$git_branch\
$git_status\
[](fg:#828aac bg:#9f9bbd)\
$nodejs\
$rust\
$golang\
$php\
[](fg:#9f9bbd bg:#262626)\
$time\
[ ](fg:#262626)\
\n$character"""

[character]
format = '[  >> ](bold #e7e7e7)'

[directory]
style = "fg:#262626 bg:#e7e7e7"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
".config" = " "

[git_branch]
symbol = ""
style = "bg:#828aac"
format = '[[ $symbol $branch ](fg:#e7e7e7 bg:#828aac)]($style)'

[git_status]
style = "bg:#828aac"
format = '[[($all_status$ahead_behind )](fg:#e7e7e7 bg:#828aac)]($style)'

[nodejs]
symbol = ""
style = "bg:#9f9bbd"
format = '[[ $symbol ($version) ](fg:#e7e7e7 bg:#9f9bbd)]($style)'

[rust]
symbol = ""
style = "bg:#9f9bbd"
format = '[[ $symbol ($version) ](fg:#e7e7e7 bg:#9f9bbd)]($style)'

[golang]
symbol = ""
style = "bg:#9f9bbd"
format = '[[ $symbol ($version) ](fg:#e7e7e7 bg:#9f9bbd)]($style)'

[php]
symbol = ""
style = "bg:#9f9bbd"
format = '[[ $symbol ($version) ](fg:#e7e7e7 bg:#9f9bbd)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#1d2230"
format = '[[   $time ](fg:#767676 bg:#262626)]($style)'
